from fastapi_mail import ConnectionConfig, FastMail
from app.core.config import MAIL_USERNAME, MAIL_PASSWORD, MAIL_FROM, MAIL_PORT, MAIL_SERVER, MAIL_TLS, MAIL_SSL, USE_CREDENTIALS

email_conf = ConnectionConfig(
    MAIL_USERNAME = MAIL_USERNAME,
    MAIL_PASSWORD = MAIL_PASSWORD,
    MAIL_FROM = MAIL_FROM,
    MAIL_PORT = MAIL_PORT,
    MAIL_SERVER = MAIL_SERVER,
    MAIL_STARTTLS = MAIL_TLS,
    MAIL_SSL_TLS = MAIL_SSL,
    USE_CREDENTIALS = USE_CREDENTIALS
)

fastmail = FastMail(email_conf)